name: Tailscale Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Login to Tailscale
      run: sudo tailscale up --authkey ${{ secrets.TAILSCALE_API_KEY }}
