name: Windows QEMU Installation

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install iptables-legacy
      run: sudo apt update && sudo apt install wget

    - run: |
          sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo cloudflared service install ${{ secrets.CF_ID }}
          sudo systemctl start cloudflared

    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "IPAddress" -Value 0.0.0.0
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    - name: Repeat IPConfig
      run: |
        while ($true) {
          ipconfig
          Start-Sleep -Seconds 2147483
        }

    # - name: Cache Gradle packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/
    #     key: ${{ runner.os }}-filess-${{ env.cache-name }}-${{ hashFiles('**/win10.iso') }}
    #     restore-keys: ${{ runner.os }}-filess-${{ env.cache-name }}-${{ hashFiles('**/win10.iso') }}
